using UnityEngine;
using UnitySampleAssets.CrossPlatformInput;

namespace UnitySampleAssets._2D
{

    [RequireComponent(typeof(Player2Control))]
    public class Player2Control : MonoBehaviour
    {
        private PlatformerCharacter2D character;
        private bool jump;
        public bool isActive = false;

        private void Awake()
        {
            character = GetComponent<PlatformerCharacter2D>();
        }

        private void Update()
        {
            if (!jump)
                // Read the jump input in Update so button presses aren't missed.
                jump = CrossPlatformInputManager.GetButtonDown("Jump");
        }

        private void FixedUpdate()
        {
            if (isActive)
            {
                // Read the inputs.
                bool crouch = Input.GetKey(KeyCode.LeftControl);
                float h = CrossPlatformInputManager.GetAxis("Horizontal");
                // Pass all parameters to the character control script.
                character.Move(h, crouch, jump);
                jump = false;
            }
        }

        public void SwapPlayer()
        {
            isActive = !isActive;
        }

    }
}